# Generated by Django 5.1 on 2024-08-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_userprofile_agent_organisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['id'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
